name: asciidoc
on:
  push:
    branches:
      - master
jobs:
  Test:
    name: Deploy docs zip
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Render guide
        run: mvn compile asciidoctor:process-asciidoc
      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/docs/advanced-vertx-guide
          CLEAN: true
